### ISSUE TITLE
License

### ISSUE THREAD

**Issue by goloroden** [joyent/node-bcrypt-pbkdf#2]
First of all: Thanks for the great work you have done with this port!
It works very well 😊

Unfortunately, there is one minor issue with this module, and this is its license… you are explicitly referring to BSD 4-clause, which contains the pretty controversial "advertising clause" (see [Wikipedia](https://en.wikipedia.org/wiki/BSD_licenses#4-clause_license_.28original_.22BSD_License.22.29) for details).

Also, the [Free Software Foundation](https://www.gnu.org/licenses/bsd.en.html) has written in a pretty detailed way on why to avoid BSD 4-clause.

Would you mind changing the license to BSD 3-clause?

As this is being used as part of [sshpk](https://github.com/joyent/node-sshpk), which is also provided by you (and which is licensed as MIT), wouldn't it even make sense to use the MIT license here as well?

**Comment by chorrell** [comment]
I'm not too familiar with the code in this project or its history, but reading the comments at the top of the code, I don't think it would be that simple to just switch licenses:

> This file is a 1:1 port from the OpenBSD blowfish.c and bcrypt_pbkdf.c. As a
> result, it retains the original copyright and license. The two files are
> under slightly different (but compatible) licenses, and are here combined in
> one file.

https://github.com/joyent/node-bcrypt-pbkdf/blob/master/index.js#L6

**Comment by arekinath** [comment]
@chorrell is correct here -- this is not our license, but rather the license of the underlying work it's derived from. We can't change it, unfortunately -- you'll have to get in contact with Niels Provos and perhaps David Mazieres and ask them to re-license the underlying C code (which was contributed to the OpenBSD project in 1997)

**Comment by arekinath** [comment]
FWIW, this module really is an *optional* dependency of `sshpk` -- you can safely remove it and `sshpk` will function as normal, just without support for encrypted `ssh-keygen -o` "new OpenSSH format" private keys. You can remove it from `package.json` and things won't break unless you try to load one of these keys (there is no module-level `require()` of this module).

It's even listed in the `optionalDependencies` list in `package.json`. Sadly `npm` treats this list exactly like the `dependencies` list and doesn't have any way to give proper optional dependencies that you can turn off without modifying something.
